# Generated by Django 3.2 on 2021-05-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210501_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_data',
            old_name='decription',
            new_name='description',
        ),
    ]
